# parameters.conf

[donut]
theta_spacing = 0.07
phi_spacing   = 0.02
R1            = 1.0
R2            = 2.0
K2            = 5.0

chars         = ".,-~:;=!*#$@"

[blackHole]
param1        = 1.0
param2        = 2.5
chars         = "◐◓◑◒"

[colors]
black  = #000000
purple = #800080
green  = #00FF00

[global]
default_screen_width = 80
default_screen_height = 24
